import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  ChevronRight,
  Upload
} from "lucide-react";
import noRecordsIllustration from "../../../assets/no-records.svg";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatCurrency, formatCurrencyPDF } from "../../../utils/financialFormatters";
import { financialReportsService } from "../../../service";

const BalanceSheet = () => {
  const navigate = useNavigate();

  const [asOf, setAsOf] = useState("");
  const [reportData, setReportData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const filtersRes = await financialReportsService.getFilters();
      if (cancelled) return;
      if (!filtersRes.success) {
        setError(filtersRes.message || "Failed to load filters");
        setIsLoading(false);
        return;
      }
      const defaultAsOf = filtersRes.data?.defaultPeriod?.to || new Date().toISOString().slice(0, 10);
      setAsOf(defaultAsOf);
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!asOf) return;
    let cancelled = false;
    (async () => {
      setIsLoading(true);
      setError("");
      const res = await financialReportsService.getBalanceSheet({ asOf });
      if (cancelled) return;
      if (!res.success) {
        setReportData(null);
        setError(res.message || "Failed to load balance sheet");
      } else {
        setReportData(res.data || null);
      }
      setIsLoading(false);
    })();
    return () => {
      cancelled = true;
    };
  }, [asOf]);

  const handleExportPDF = () => {
    if (!reportData) return;

    const doc = new jsPDF("p", "pt", "a4");
    const pageWidth = doc.internal.pageSize.width;

    // --- 1. Top Header ---
    doc.setFillColor(125, 30, 219); // #7D1EDB
    doc.rect(40, 40, pageWidth - 80, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "normal");
    doc.text("SUH TECH", 50, 65);

    doc.setFontSize(18);
    doc.text("BALANCE SHEET REPORT", pageWidth - 50, 65, { align: "right" });

    // --- 2. Sub-header ---
    doc.setFillColor(237, 232, 252); // #EDE8FC
    doc.rect(40, 80, pageWidth - 80, 40, "F");

    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Company:", 50, 95);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.company || "Organization", 95, 95);

    doc.setFont("helvetica", "bold");
    doc.text("Period:", 50, 110);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.period || asOf, 85, 110);

    const now = new Date();
    const formattedDate = `${now.getDate()} ${now.toLocaleString("default", { month: "long" })} ${now.getFullYear()}, ${now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`;

    doc.setFont("helvetica", "bold");
    doc.text("Generated:", pageWidth - 190, 95);
    doc.setFont("helvetica", "normal");
    doc.text(formattedDate, pageWidth - 140, 95);

    doc.setFont("helvetica", "bold");
    doc.text("Generated By:", pageWidth - 190, 110);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.generatedBy || "Admin", pageWidth - 125, 110);

    let currentY = 135;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.rect(40, currentY, pageWidth - 80, 20);
    
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Statement Date:", 50, currentY + 13);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.statementDate || asOf, 115, currentY + 13);
    
    doc.setFont("helvetica", "bold");
    doc.text("Entity:", (pageWidth / 2) - 40, currentY + 13);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.company || "Organization", (pageWidth / 2) - 10, currentY + 13);

    doc.setFont("helvetica", "bold");
    doc.text("Currency:", pageWidth - 140, currentY + 13);
    doc.setFont("helvetica", "normal");
    doc.text(reportData.meta?.currency || "INR", pageWidth - 100, currentY + 13);

    currentY += 40;

    // --- 3. Financial Summary ---
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Financial Summary", 40, currentY);
    currentY += 20;

    const summaryDataPDF = [
      { title: "Total Assets", amount: formatCurrencyPDF(reportData.totalAssets), subtitle: "Current + Non-Current" },
      { title: "Total Liabilities", amount: formatCurrencyPDF(reportData.totalLiabilities), subtitle: "Current + Non-Current" },
      { title: "Total Equity", amount: formatCurrencyPDF(reportData.totalEquity), subtitle: "Shareholder's Equity" },
      { title: "Current Ratio", amount: String(reportData.currentRatio ?? 0), subtitle: "Assets / Liabilities" },
    ];

    const boxWidth = (pageWidth - 80 - 45) / 4;
    summaryDataPDF.forEach((item, index) => {
      const x = 40 + index * (boxWidth + 15);
      doc.setDrawColor(240, 240, 240);
      doc.setFillColor(255, 255, 255);
      doc.setLineWidth(1);
      doc.roundedRect(x, currentY, boxWidth, 60, 4, 4, "FD");

      doc.setTextColor(100, 100, 100);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(item.title, x + 8, currentY + 15);

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(item.amount, x + 8, currentY + 35);

      doc.setTextColor(100, 100, 100);
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.text(item.subtitle, x + 8, currentY + 50);
    });

    currentY += 80;

    // --- 4. Assets and Liabilities Titles ---
    const halfWidth = (pageWidth - 80 - 15) / 2;
    doc.setFillColor(242, 238, 255); // #F2EEFF (very light purple)
    doc.rect(40, currentY, halfWidth, 20, "F");
    doc.rect(40 + halfWidth + 15, currentY, halfWidth, 20, "F");

    doc.setTextColor(40, 40, 40);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Assets", 50, currentY + 14);
    doc.text("Liabilities & Equity", 40 + halfWidth + 15 + 10, currentY + 14);

    currentY += 35;

    let leftY = currentY;
    let rightY = currentY;

    const drawTable = (yPos, xPos, tableWidth, title, rows, totalsArray) => {
      if (title) {
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(title, xPos, yPos + 10);
        yPos += 20;
      }
      
      const bodyRows = rows.map(r => [r.name, formatCurrencyPDF(r.amount)]);
      const bodyLen = bodyRows.length;
      totalsArray.forEach(t => bodyRows.push([t.label, formatCurrencyPDF(t.value)]));

      autoTable(doc, {
        startY: yPos,
        head: [["Name", "Amount(Rs)"]],
        body: bodyRows,
        theme: "plain",
        headStyles: {
          fillColor: [125, 30, 219],
          textColor: 255,
          fontSize: 9,
          halign: "center",
          cellPadding: 6,
        },
        bodyStyles: {
          fontSize: 9,
          halign: "center",
          textColor: 40,
          cellPadding: 6,
        },
        columnStyles: { 0: { halign: "left" }, 1: { halign: "right" } },
        margin: { left: xPos, right: pageWidth - xPos - tableWidth },
        didParseCell: function (data) {
          if (data.section === "body" && data.row.index >= bodyLen) {
            const totalIndex = data.row.index - bodyLen;
            const tDef = totalsArray[totalIndex];
            if (tDef.isGrandTotal) {
              data.cell.styles.fillColor = [125, 30, 219];
              data.cell.styles.textColor = 255;
            } else {
              data.cell.styles.fillColor = [238, 236, 255];
              data.cell.styles.textColor = 0;
            }
            data.cell.styles.fontStyle = "bold";
          }
        },
      });
      
      const finalY = doc.lastAutoTable.finalY;
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(1);
      doc.rect(xPos, yPos, tableWidth, finalY - yPos, "S");
      
      return finalY + 15;
    };

    leftY = drawTable(leftY, 40, halfWidth, "Current Assets", reportData.currentAssets, [
      { label: "TOTAL CURRENT ASSETS", value: reportData.totalCurrentAssets }
    ]);

    leftY = drawTable(leftY, 40, halfWidth, "Non-Current Assets", reportData.nonCurrentAssets, [
      { label: "TOTAL NON-CURRENT ASSETS", value: reportData.totalNonCurrentAssets },
      { label: "TOTAL ASSETS", value: reportData.totalAssets, isGrandTotal: true }
    ]);

    rightY = drawTable(rightY, 40 + halfWidth + 15, halfWidth, "Current Liabilities", reportData.currentLiabilities, [
      { label: "TOTAL CURRENT LIABILITIES", value: reportData.totalCurrentLiabilities }
    ]);

    rightY = drawTable(rightY, 40 + halfWidth + 15, halfWidth, "Non-Current Liabilities", reportData.nonCurrentLiabilities, [
      { label: "TOTAL NON-CURRENT LIABILITIES", value: reportData.totalNonCurrentLiabilities }
    ]);

    rightY = drawTable(rightY, 40 + halfWidth + 15, halfWidth, "Equity", reportData.equity, [
      { label: "TOTAL EQUITY", value: reportData.totalEquity },
      { label: "TOTAL LIABILITIES & EQUITY", value: reportData.totalLiabilitiesEquity, isGrandTotal: true }
    ]);

    currentY = Math.max(leftY, rightY) + 10;
    
    // Page break logic if needed
    if (currentY > doc.internal.pageSize.height - 150) {
        doc.addPage();
        currentY = 40;
    }

    const finalSummaryRows = [
      ["Total Assets", formatCurrencyPDF(reportData.totalAssets)],
      ["Total Liabilities", formatCurrencyPDF(reportData.totalLiabilitiesEquity)],
      ["Total Equity", formatCurrencyPDF(reportData.totalEquity)],
      ["Liabilities + Equity", formatCurrencyPDF(reportData.totalLiabilitiesEquity)]
    ];

    const finalSummaryStartY = currentY;

    autoTable(doc, {
      startY: finalSummaryStartY,
      head: [["Item", "Amount(Rs)"]],
      body: finalSummaryRows,
      theme: "plain",
      headStyles: {
        fillColor: [125, 30, 219],
        textColor: 255,
        fontSize: 10,
        halign: "center",
        cellPadding: 8,
      },
      bodyStyles: {
        fontSize: 10,
        halign: "center",
        textColor: 40,
        cellPadding: 8,
      },
      columnStyles: { 0: { halign: "center" }, 1: { halign: "center" } }, 
      margin: { left: 40, right: 40 },
    });
    
    currentY = doc.lastAutoTable.finalY + 1;
    
    // Draw border for final summary table
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(1);
    doc.rect(40, finalSummaryStartY - 1, pageWidth - 80, currentY - finalSummaryStartY, "S");
    
    // Bottom Green Bar
    doc.setFillColor(219, 251, 230);
    doc.rect(40, currentY, pageWidth - 80, 25, "F");
    
    doc.setTextColor(50, 187, 99); 
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("BALANCE SHEET BALANCED", 50, currentY + 16);
    doc.text("ASSETS = LIABILITIES + EQUITY", pageWidth - 50, currentY + 16, { align: "right" });
    
    doc.save("Balance_Sheet_Report.pdf");
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px] text-gray-500 font-medium">
        Loading Balance Sheet Data...
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px] text-red-500 font-medium">
        {error}
      </div>
    );
  }

  const hasData =
    (reportData?.currentAssets?.length || 0) +
      (reportData?.nonCurrentAssets?.length || 0) +
      (reportData?.currentLiabilities?.length || 0) +
      (reportData?.nonCurrentLiabilities?.length || 0) +
      (reportData?.equity?.length || 0) >
    0;

  // Reusable sub-table renderer
  const renderTable = (data, totalLabel, totalValue) => {
    if (!hasData) {
      return (
        <div className="flex flex-col items-center justify-center bg-white py-10 min-h-[200px]">
          <img
            src={noRecordsIllustration}
            alt="No Data found"
            className="mb-2"
            style={{ width: "100%", maxWidth: "200px", height: "auto" }}
          />
          <h3 className="text-center mb-1 text-black font-bold text-[18px]" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            No Data found
          </h3>
          <p className="text-center text-[#B0B0B0] font-medium text-[14px]" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            There is no data to show at the moment.
          </p>
        </div>
      );
    }

    return (
      <div className="flex flex-col bg-white">
        {data.map((row, idx) => (
          <div
            key={idx}
            className="flex justify-between items-center text-[13px] sm:text-[14px] px-4 py-3 hover:bg-gray-50 transition-colors"
          >
            <div className="font-normal text-[#1E1E1E]">{row.name}</div>
            <div className="font-normal text-[#1E1E1E]">{formatCurrency(row.amount)}</div>
          </div>
        ))}
        {/* Subtotal Row */}
        {totalLabel && (
          <div className="flex justify-between items-center text-[13px] sm:text-[14px] bg-[#EEECFF] px-4 py-3 mt-1">
            <div className="text-[#1E1E1E]" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>{totalLabel}</div>
            <div className="text-[16px] text-[#1E1E1E]" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>{formatCurrency(totalValue)}</div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div
      className="bg-white px-2 sm:px-4 md:px-6 py-2 sm:py-4 mx-0 sm:mx-4 mt-2 sm:mt-4 mb-4 rounded-xl h-[calc(100vh-8rem)] md:h-[calc(100vh-10rem)] overflow-y-auto"
      style={{ fontFamily: "Poppins, sans-serif" }}
    >
      {/* Breadcrumb */}
      <div className="flex items-center text-xs sm:text-sm mb-2">
        <div
          className="flex items-center gap-1 cursor-pointer"
          onClick={() => navigate("/hrms")}
        >
          <ArrowLeft size={12} className="text-[#8B8D97]" />
          <span className="text-[#7D1EDB] font-normal">HRMS Dashboard</span>
        </div>
        <ChevronRight size={14} className="mx-1 text-[#8B8D97]" />
        <span className="text-[#667085]">Balance Sheet</span>
      </div>

      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-4">
        <h1
          className="text-gray-900"
          style={{
            fontFamily: "'Nunito Sans', sans-serif",
            fontWeight: 400,
            fontSize: "20px",
            color: "#494949",
            lineHeight: "100%",
          }}
        >
          Balance Sheet
        </h1>
        <button
          onClick={handleExportPDF}
          className="text-white font-medium transition-colors flex items-center justify-center cursor-pointer hover:bg-purple-700"
          style={{
            width: "165px",
            height: "40px",
            padding: "10px 16px",
            borderRadius: "26px",
            background: "#7D1EDB",
            fontSize: "14px",
          }}
        >
          Generate Report
        </button>
      </div>

      {/* Buttons Row */}
      <div className="flex flex-wrap gap-4 mb-6 items-center">
        <label
          className="flex items-center justify-between gap-2 px-4 py-2 bg-[#F3F0FF] rounded-lg cursor-pointer"
          style={{ color: "#7D1EDB", fontSize: "14px" }}
        >
          Statement Date
          <input
            type="date"
            value={asOf}
            onChange={(e) => setAsOf(e.target.value)}
            className="bg-transparent outline-none text-[#7D1EDB] cursor-pointer"
          />
        </label>

        <button
          onClick={handleExportPDF}
          className="flex items-center justify-between gap-2 px-4 py-2 bg-white rounded-3xl border cursor-pointer border-[#7D1EDB]"
          style={{
            color: "#7D1EDB",
            fontSize: "14px",
          }}
        >
          Export PDF
          <Upload size={16} className="text-[#7D1EDB]" />
        </button>
      </div>

      {/* Two Column Layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Left Column - ASSETS */}
        <div className="border border-[#E4E0E0] rounded-[8px] p-2 sm:p-4 bg-white flex flex-col w-full h-full">
          <h2 className="text-[16px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            Assets
          </h2>
          
          {/* Current Asset */}
          <h3 className="text-[14px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            Current Asset
          </h3>
          <div className="border border-[#E4E0E0] rounded-lg overflow-hidden flex flex-col mb-4">
            <div className="flex justify-between text-[13px] text-[#808080] bg-white border-b border-[#E4E0E0] px-4 py-3">
              <span className="font-normal text-center w-full sm:w-auto sm:text-left sm:ml-8">Name</span>
              <span className="font-normal text-center w-full sm:w-auto sm:text-right">Amount</span>
            </div>
            {renderTable(reportData?.currentAssets || [], "TOTAL CURRENT ASSETS", reportData?.totalCurrentAssets || 0)}
          </div>

          {/* Non-Current Assets */}
          <div>
            <h3 className="text-[14px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
              Non-Current Assets
            </h3>
            <div className="border border-[#E4E0E0] rounded-lg overflow-hidden flex flex-col">
              <div className="flex justify-between text-[13px] text-[#808080] bg-white border-b border-[#E4E0E0] px-4 py-3">
                <span className="font-normal text-center w-full sm:w-auto sm:text-left sm:ml-8">Name</span>
                <span className="font-normal text-center w-full sm:w-auto sm:text-right">Amount</span>
              </div>
              {renderTable(reportData?.nonCurrentAssets || [], "TOTAL NON-CURRENT ASSETS", reportData?.totalNonCurrentAssets || 0)}
            </div>
          </div>

          {/* Final Left Column Total */}
          {hasData && (
            <div className="flex justify-between items-center text-[13px] sm:text-[14px] bg-[#756FCC] text-white rounded-[8px] px-4 py-3 mt-4">
              <div className="font-medium">TOTAL ASSETS</div>
              <div className="text-[18px]">{formatCurrency(reportData?.totalAssets || 0)}</div>
            </div>
          )}
        </div>

        {/* Right Column - LIABILITIES & EQUITY */}
        <div className="border border-[#E4E0E0] rounded-[8px] p-2 sm:p-4 bg-white flex flex-col w-full h-full">
          <h2 className="text-[16px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            Liabilities & Equity
          </h2>

          {/* Current Liabilities */}
          <h3 className="text-[14px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            Current Liabilities
          </h3>
          <div className="border border-[#E4E0E0] rounded-lg overflow-hidden flex flex-col mb-4">
            <div className="flex justify-between text-[13px] text-[#808080] bg-white border-b border-[#E4E0E0] px-4 py-3">
              <span className="font-normal text-center w-full sm:w-auto sm:text-left sm:ml-8">Name</span>
              <span className="font-normal text-center w-full sm:w-auto sm:text-right">Amount</span>
            </div>
            {renderTable(reportData?.currentLiabilities || [], "TOTAL CURRENT LIABILITIES", reportData?.totalCurrentLiabilities || 0)}
          </div>

          {/* Non-Current Liabilities */}
          <h3 className="text-[14px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
            Non-Current Liabilities
          </h3>
          <div className="border border-[#E4E0E0] rounded-lg overflow-hidden flex flex-col mb-4">
            <div className="flex justify-between text-[13px] text-[#808080] bg-white border-b border-[#E4E0E0] px-4 py-3">
              <span className="font-normal text-center w-full sm:w-auto sm:text-left sm:ml-8">Name</span>
              <span className="font-normal text-center w-full sm:w-auto sm:text-right">Amount</span>
            </div>
            {renderTable(reportData?.nonCurrentLiabilities || [], "TOTAL NON-CURRENT LIABILITIES", reportData?.totalNonCurrentLiabilities || 0)}
          </div>

          {/* Equity */}
          <div>
            <h3 className="text-[14px] text-[#1E1E1E] mb-2" style={{ fontFamily: "'Nunito Sans', sans-serif" }}>
              Equity
            </h3>
            <div className="border border-[#E4E0E0] rounded-lg overflow-hidden flex flex-col">
              <div className="flex justify-between text-[13px] text-[#808080] bg-white border-b border-[#E4E0E0] px-4 py-3">
                <span className="font-normal text-center w-full sm:w-auto sm:text-left sm:ml-8">Name</span>
                <span className="font-normal text-center w-full sm:w-auto sm:text-right">Amount</span>
              </div>
              {renderTable(reportData?.equity || [], "TOTAL EQUITY", reportData?.totalEquity || 0)}
            </div>
          </div>

          {/* Final Right Column Total */}
          {hasData && (
            <div className="flex justify-between items-center text-[13px] sm:text-[14px] bg-[#756FCC] text-white rounded-[8px] px-4 py-3 mt-4">
              <div className="font-medium">TOTAL LIABILITIES & EQUITY</div>
              <div className="text-[18px]">{formatCurrency(reportData?.totalLiabilitiesEquity || 0)}</div>
            </div>
          )}
        </div>

      </div>
    </div>
  );
};

export default BalanceSheet;
