import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { BriefcaseBusiness, Calendar, Plus, Search, Users } from 'lucide-react';
import { projectOptions, projectService } from '../../../features/projects/projectService';
import { demoProjects } from '../../../features/projects/demoData';

const tone = (value) => ({ COMPLETED: 'bg-emerald-50 text-emerald-700', IN_PROGRESS: 'bg-blue-50 text-blue-700', IN_REVIEW: 'bg-amber-50 text-amber-700', BLOCKED: 'bg-rose-50 text-rose-700' }[value] || 'bg-slate-100 text-slate-600');
const date = (value) => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : '—';
const blank = { name: '', description: '', status: 'TODO', priority: 'MEDIUM', startDate: '', dueDate: '' };

export default function Projects() {
  const navigate = useNavigate();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [usingDemo, setUsingDemo] = useState(false);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState('');
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  const load = async () => { try { setLoading(true); setError(''); const data = await projectService.list({ search: query, status, priority }); setItems(data.items ?? data.projects ?? data ?? []); setUsingDemo(false); } catch { const q = query.toLowerCase(); setItems(demoProjects.filter((p) => (!q || `${p.name} ${p.description}`.toLowerCase().includes(q)) && (!status || p.status === status) && (!priority || p.priority === priority))); setUsingDemo(true); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [query, status, priority]);
  const counts = useMemo(() => ({ total: items.length, active: items.filter((x) => x.status === 'IN_PROGRESS').length, completed: items.filter((x) => x.status === 'COMPLETED').length }), [items]);
  const submit = async (e) => { e.preventDefault(); if (form.dueDate && form.startDate && form.dueDate < form.startDate) return toast.error('Due date must be after start date'); try { setSaving(true); await projectService.create(form); toast.success('Project created'); setForm(blank); setShowForm(false); await load(); } catch { setItems((current) => [{ ...form, id: `demo-${Date.now()}`, progress: 0 }, ...current]); setForm(blank); setShowForm(false); setUsingDemo(true); toast.success('Project created in demo mode'); } finally { setSaving(false); } };
  const archive = async (event, id) => { event.preventDefault(); event.stopPropagation(); if (!window.confirm('Archive this project? Its tasks will no longer appear in active views.')) return; try { await projectService.archive(id); toast.success('Project archived'); load(); } catch { setItems((current) => current.filter((p) => p.id !== id)); toast.success('Project archived in demo mode'); } };
  return <div className="min-h-[calc(100vh-88px)] rounded-2xl bg-[#f7f7fa] p-4 sm:p-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-1 flex items-center gap-2 text-sm font-semibold text-violet-600"><BriefcaseBusiness size={17} /> Work management</div><h1 className="text-2xl font-bold text-slate-900">Projects</h1><p className="mt-1 text-sm text-slate-500">Plan work, assign your team, and track delivery.</p></div><button onClick={() => setShowForm(true)} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-200"><Plus size={17} /> Create project</button></div>
    <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3">{[['All projects', counts.total, 'bg-violet-50 text-violet-600'], ['In progress', counts.active, 'bg-blue-50 text-blue-600'], ['Completed', counts.completed, 'bg-emerald-50 text-emerald-600']].map(([label, value, color]) => <div key={label} className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className={`mb-3 grid h-9 w-9 place-items-center rounded-xl ${color}`}><BriefcaseBusiness size={17} /></div><p className="text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="flex flex-wrap gap-2 border-b p-4"><div className="flex min-w-[220px] flex-1 items-center gap-2 rounded-xl border px-3 py-2"><Search size={16} className="text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search projects…" className="w-full text-sm outline-none" /></div>{[['Status', status, setStatus, projectOptions.statuses], ['Priority', priority, setPriority, projectOptions.priorities]].map(([label, value, setter, options]) => <select aria-label={label} key={label} value={value} onChange={(e) => setter(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">All {label.toLowerCase()}es</option>{options.map((x) => <option key={x} value={x}>{x.replaceAll('_', ' ')}</option>)}</select>)}</div>
      {error ? <div className="p-12 text-center"><p className="text-rose-600">{error}</p><button onClick={load} className="mt-3 text-sm font-semibold text-violet-600">Try again</button></div> : loading ? <div className="space-y-3 p-5">{[1,2,3].map((x) => <div key={x} className="h-24 animate-pulse rounded-xl bg-slate-100" />)}</div> : !items.length ? <div className="p-14 text-center text-sm text-slate-500">No projects found. Create the first project to get started.</div> : <div className="divide-y">{items.map((p) => <div role="button" tabIndex={0} onClick={() => navigate(`/hrms/projects/${p.id}`)} onKeyDown={(e) => e.key === 'Enter' && navigate(`/hrms/projects/${p.id}`)} key={p.id} className="flex cursor-pointer flex-wrap items-center gap-4 p-4 transition hover:bg-slate-50"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><BriefcaseBusiness size={19}/></div><div className="min-w-[180px] flex-1"><p className="font-semibold text-slate-900">{p.name}</p><p className="mt-1 line-clamp-1 text-sm text-slate-500">{p.description || 'No description'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone(p.status)}`}>{(p.status || 'TODO').replaceAll('_', ' ')}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{p.priority || 'MEDIUM'}</span><div className="w-32"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Progress</span><span>{p.progress ?? 0}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-violet-600" style={{width:`${p.progress ?? 0}%`}}/></div></div><div className="text-xs text-slate-500"><Calendar size={14} className="mr-1 inline"/>{date(p.dueDate)}</div><button onClick={(e) => archive(e, p.id)} className="text-xs font-semibold text-rose-600">Archive</button></div>)}</div>}</section>
    {showForm && <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-900/40 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold">Create project</h2><p className="mt-1 text-sm text-slate-500">Projects are visible only to authorized members.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium">Project name<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="sm:col-span-2 text-sm font-medium">Description<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border p-2.5" /></label>{[['Status','status',projectOptions.statuses],['Priority','priority',projectOptions.priorities]].map(([label,key,options])=><label key={key} className="text-sm font-medium">{label}<select value={form[key]} onChange={(e)=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5">{options.map((x)=><option key={x}>{x}</option>)}</select></label>)}<label className="text-sm font-medium">Start date<input type="date" value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm font-medium">Due date<input type="date" value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setShowForm(false)} disabled={saving} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">{saving ? 'Creating…' : 'Create project'}</button></div></form></div>}
  </div>;
}
