export const seedAnnouncements = [
  { id:'ann-1', title:'Annual Town Hall & FY26 Vision', description:'Join the leadership team as we review our progress and share the roadmap for the year ahead.', content:'<h2>Building what comes next, together</h2><p>Join the leadership team for our annual town hall. We will review company performance, celebrate team wins, and share our FY26 priorities.</p><p>The session ends with an open Q&A. Please submit questions in advance or ask them live.</p>', type:'Company Update', priority:'Important', audience:'All Employees', departments:['All departments'], employees:[], author:'Ananya Mehta', createdAt:'2026-08-08T10:30:00', publishedAt:'2026-08-10T09:00:00', updatedAt:'2026-08-10T09:00:00', status:'Published', expiryDate:'2026-09-10', attachments:[{id:'f1',name:'FY26-town-hall-agenda.pdf',size:'1.8 MB',type:'PDF'}], reads:128, recipients:156 },
  { id:'ann-2', title:'Updated Hybrid Work Policy', description:'The revised hybrid work guidelines take effect from September 1.', content:'<h2>Updated workplace guidelines</h2><p>From September 1, teams may designate two anchor days each week. Please coordinate schedules with your manager and review the attached policy.</p>', type:'Policy', priority:'Urgent', audience:'All Employees', departments:['All departments'], employees:[], author:'Rhea Kapoor', createdAt:'2026-08-09T14:00:00', publishedAt:'2026-08-11T11:15:00', updatedAt:'2026-08-11T11:15:00', status:'Published', expiryDate:'2026-10-01', attachments:[{id:'f2',name:'Hybrid-work-policy.pdf',size:'824 KB',type:'PDF'}], reads:96, recipients:156 },
  { id:'ann-3', title:'Engineering Maintenance Window', description:'Planned infrastructure maintenance this Saturday between 10 PM and midnight.', content:'<p>Production systems will undergo planned maintenance. Customer-facing downtime is not expected, but internal dashboards may be briefly unavailable.</p>', type:'Maintenance', priority:'Important', audience:'Specific Departments', departments:['Engineering','IT'], employees:[], author:'Kabir Shah', createdAt:'2026-08-10T12:20:00', scheduledAt:'2026-08-15T18:00:00', updatedAt:'2026-08-10T12:20:00', status:'Scheduled', expiryDate:'2026-08-17', attachments:[], reads:0, recipients:48 },
  { id:'ann-4', title:'Quarterly Learning Allowance', description:'A quick guide to claiming your professional development allowance.', content:'<p>Every employee can claim up to ₹15,000 per quarter for eligible learning expenses. Add examples and links before publishing.</p>', type:'Benefits', priority:'Normal', audience:'All Employees', departments:['All departments'], employees:[], author:'Ananya Mehta', createdAt:'2026-08-11T16:10:00', updatedAt:'2026-08-12T09:20:00', status:'Draft', expiryDate:'', attachments:[], reads:0, recipients:156 },
  { id:'ann-5', title:'July Culture Champions', description:'Celebrating colleagues who brought our values to life this month.', content:'<p>Congratulations to this month’s Culture Champions. Thank you for making Orga a thoughtful, inclusive place to work.</p>', type:'Recognition', priority:'Normal', audience:'All Employees', departments:['All departments'], employees:[], author:'People Team', createdAt:'2026-07-29T09:00:00', publishedAt:'2026-07-30T09:00:00', updatedAt:'2026-08-08T11:00:00', status:'Archived', expiryDate:'2026-08-07', attachments:[], reads:142, recipients:154 },
];

export const departments = ['Engineering','Design','People & Culture','Finance','Marketing','Sales','IT'];
export const employees = ['Aarav Sharma','Diya Patel','Ishaan Verma','Meera Nair','Vivaan Gupta'];
export const blankAnnouncement = { title:'', description:'', content:'', type:'Company Update', priority:'Normal', audience:'All Employees', departments:[], employees:[], status:'Draft', expiryDate:'', attachments:[], author:'Ananya Mehta' };
